### ISSUE TITLE
The "Respond to Call" button doesn't work for EMS

### ISSUE THREAD

**Issue by ClockworkQueen13** [Project-Sloth/ps-mdt#154]
![image](https://user-images.githubusercontent.com/114237119/222831069-5309b275-aa1d-4abe-a948-e5849ab6badc.png)
Here is a photo example of a police call response, EMS cannot do this. 
- I am on the most recent MDT update.
- There are no script errors.  
- I have been having this issue since September, I was told to create an issue on the GitHub in Project Sloth!

**Comment by Crayons0814** [comment]
the issue is in the server main.lua, there is a function to check if the user is Police, it is used in the events to access the call response but there is nothing for ambulance. that is why only police can access it for reference the lines are 1328 and 1340 for whoever wants to fix. I just removed the function and replaced it with directly calling Config.Policejobs and Config.AmbulanceJobs, might not be then best option but it works for me without issue

**Comment by ClockworkQueen13** [comment]
> 

Would you mind posting your code? I just want to be sure I do it right! Thank you so so much for the fix! It's been driving me crazy for months!

**Comment by Crayons0814** [comment]
again i don't know if my fix is the best way but you change line 1320 and 1332 from **if IsPolice(Player.PlayerData.job.name) then** to **if Config.PoliceJobs or Config.AmbulanceJobs(Player.PlayerData.job.name) then** this works for me if it doesn't for you i don't have a solution so use at your own risk

**Comment by MonkeyWhisper** [comment]
> again i don't know if my fix is the best way but you change line 1320 and 1332 from **if IsPolice(Player.PlayerData.job.name) then** to **if Config.PoliceJobs or Config.AmbulanceJobs(Player.PlayerData.job.name) then** this works for me if it doesn't for you i don't have a solution so use at your own risk

Yes, this works. Can you send in a PR to make sure you get credits?

**Comment by Crayons0814** [comment]
PR made you should see it

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-mdt/pull/158
