### ISSUE TITLE
EMS MDT - Profile page not displaying image

### ISSUE THREAD

**Issue by BackSH00TER** [Project-Sloth/ps-mdt#302]
When looking at a profile page as an EMS, the profile image is not loading even when it is set.
![image](https://user-images.githubusercontent.com/18689469/233872494-1ab450da-2d6f-4a81-89d0-c199f8a30aef.png)

Additionally, the profile page is showing Convictionsa and Incidents, which are police specific. Instead this should show their ICU reports + injuries

**Comment by MonkeyWhisper** [comment]
Yeah, so it's not that it's broken
It's because the person that first creates the record only retrieves the info related to that department 

So that only people associated with the particular job type can see the info

![image](https://user-images.githubusercontent.com/82112471/234741318-6c582db8-8640-41d3-b24b-a38a1d4a1b0e.png)
