### ISSUE TITLE
MDT still taking a while time to open after newest version

### ISSUE THREAD

**Issue by MonkeyWhisper** [Project-Sloth/ps-mdt#419]
https://github.com/Project-Sloth/ps-dispatch/issues/216

**Comment by Gnavling** [comment]
I'm also having this issue whenever the player count goes above 30 ish. Just updated today

**Comment by xFutte** [comment]
I think it is what has been added in commit bb2fe4598960f704d8c35ed0d06bf373f51908ee. There are loops within loops, which blocks the thread.

**Comment by Gnavling** [comment]
Ended up timing out my server when we went above 100 players

**Comment by MonkeyWhisper** [comment]
Although it's a good improvement, that PR does not fix slow opening

**Comment by Gnavling** [comment]
I reverted to my previous version of the MDT but still kept the latest version of dispatch and I still experienced performance issues on my server even though dispatch wasn't populating the recent calls. Still a bit of a delay to opening the MDT. Not sure if that's useful but wanted to include it. 

The MDT still gets progressively slower with v2.5.4 and v2.0.6 of dispatch. I believe the issue is with ps-dispatch.

**Comment by xFutte** [comment]
@Gnavling I have pushed a performance improvement in a branch. After testing, it should be merged into main. Then you can try it out and see if that improves it.

**Comment by Gnavling** [comment]
@xFutte I'll test it, appreciate you

**Comment by xFutte** [comment]
@Gnavling Note that the branch is within ps-dispatch.

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-mdt/pull/428

**Comment by MonkeyWhisper** [comment]
Reverted https://github.com/Project-Sloth/ps-mdt/commit/6dd8af7032c90bc9565e6f7f2f3c965223c30afc 

Too many ticks server sided

**Comment by MonkeyWhisper** [comment]
Fixed on 
https://github.com/Project-Sloth/ps-mdt/pull/434
https://github.com/Project-Sloth/ps-dispatch/pull/230

**Comment by Gnavling** [comment]
Still super slow to open on the latest versions of ps-mdt and ps-dispatch
