### ISSUE TITLE
Didn't get dispatch call on MDT

### ISSUE THREAD

**Issue by Devil-panda** [Project-Sloth/ps-mdt#86]
i recently install ps-mdt and ps-dispatch but when dispatch pop up but in mdt it didn't show up

**Comment by AkinoKitsu** [comment]
Seems to be caused by [this commit](https://github.com/Project-Sloth/ps-mdt/commit/a49c866e9361645081f6effa1f0338ba0d3862db)
You can undo the changes from that commit and it should work again.

If you haven't already, make sure ps-dispatch is started *before* ps-mdt, that may resolve the issue for you.

**Comment by Devil-panda** [comment]
okay! let me try

**Comment by MonkeyWhisper** [comment]
Fixed, download latest repo.
